<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      //如果then方法中返回了一个Promise对象，那就以这个对象为准，返回它的结果
      //   let p = new Promise((resolve, reject) => {
      //     resolve(1);
      //   });

      //   p.then((data) => {
      //     return new Promise((resolve, reject) => {
      //       resolve(2);
      //     });
      //   }).then((data) => {
      //     console.log(data);
      //   });

      //Promise.resolve()方法，接受一个值，将现有对象转为Promise对象
      //   let p1 = Promise.resolve(value);

      //Promise.reject()方法，返回一个带有拒绝原因的Promise对象
      //   let p2 = Promise.reject(value);

      //Promise.all()用于将多个Promise实例包装成一个新的Promise实例，参数为一组Promise实例组成的数组
      //   let p3 = Promise.resolve(1);
      //   let p4 = Promise.resolve(2);
      //   let p5 = Promise.resolve(3);

      //   let p = Promise.all([p1, p2, p3]);

      //   p.then((data) => {
      //     console.log(data);
      //   });

      //   const fn = () => console.log("fn");
      //   (() => new Promise((resolve) => resolve(fn())))()
      //     .then(() => {
      //       console.log(222);
      //     })
      //     .catch((err) => {
      //       console.log(err);
      //     });

      //   const fn = () => console.log("fn");
      //   (async () => fn())()
      //     .then(() => {
      //       console.log(222);
      //     })
      //     .catch((err) => {
      //       console.log(err);
      //     });

      //   const fn = () => console.log("fn");
      //   Promise.try(fn)
      //     .then(() => {
      //       console.log(222);
      //     })
      //     .catch((err) => {
      //       console.log(err);
      //     });

      //   console.log("111");

      //异步回调中抛错catch捕捉不到
      //   const p = new Promise((resolve, reject) => {
      //     throw new Error("这是一个错误");
      //   });
      //   p.catch((err) => {
      //     console.log(error);
      //   });

      //使用try catch捕获异常主动触发reject
      // const p = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     try {
      //       throw new Error("error");
      //     } catch (e) {
      //       reject(e);
      //     }
      //   }, 0);
      // });
      // p.catch((err) => {
      //   console.log(error);
      // });

      // Promise优/缺
      // 优点:
      // Promise用同步的方式写异步的代码，避免了层层嵌套的回调函数
      // Promise对象提供了统一的接口，使得控制异步操作更加容易
      // 链式操作，可以在then中继续写Promise对象并返回，然后继续调用then来进行回调操作
      // 缺点:
      // Promise对象一旦新建就会立即执行，无法中途取消
      // 若不设置回调函数，Promise内部会抛出错误，不会流到外部
      // 当处于pending状态时，无法得知当前处于哪一阶段
      // 用多了Promise后代码一眼看上去都是promise的API，而且链式语法总觉得不好看，不优雅
      function Promise(executor) {
        this.state = "pending";
        this.value = undefined;
        this.reason = undefined;

        this.onResolvedCallbacks = [];
        this.onRejectedCallbacks = [];
        //立即执行
        try {
          executor(resolve, reject);
        } catch (err) {
          reject(err);
        }
        let _this = this;

        function resolve(value) {
          if (_this.state === "pending") {
            _this.value = value;
            _this.onResolvedCallbacks.forEach((cb) => cb(value));
            _this.state = "resolved";
          }
        }
        function reject(reason) {
          if (_this.state === "pending") {
            _this.reason = reason;
            _this.onRejectedCallbacks.forEach((cb) => cb(reason));
            _this.state = "rejected";
          }
        }
      }
      Promise.prototype.then = function (onFulfilled, onRejected) {
        onFulfilled =
          typeof onFulfilled === "function" ? onFulfilled : (value) => value;
        onRejected =
          typeof onRejected === "function"
            ? onRejected
            : (err) => {
                throw err;
              };

        let promise2 = new Promise((resolve, reject) => {
          if (this.state === "pending") {
            // if (typeof onFulfilled === "function") {
            // this.onResolvedCallbacks.push(onFulfilled);
            // }
            // if (typeof onRejected === "function") {
            // this.onRejectedCallbacks.push(onRejected);
            // }
            this.onResolvedCallbacks.push(() => {
              setTimeout(() => {
                try {
                  let x = onFulfilled(this.value);
                  resolvePromise(promise2, x, resolve, reject);
                } catch (e) {
                  reject(e);
                }
              }, 0);
            });
            this.onRejectedCallbacks.push(() => {
              setTimeout(() => {
                try {
                  let x = onRejected(this.value);
                  resolvePromise(promise2, x, resolve, reject);
                } catch (e) {
                  reject(e);
                }
              }, 0);
            });
          }

          if (this.state === "resolved") {
            // if (typeof onFulfilled === "function") {
            // onFulfilled(this.value);
            // }
            setTimeout(() => {
              try {
                let x = onFulfilled(this.value);
                resolvePromise(promise2, x, resolve, reject);
              } catch {
                reject(e);
              }
            }, 0);
          }
          if (this.state === "rejected") {
            // if (typeof onRejected === "function") {
            // onRejected(this.reason);
            // }
            setTimeout(() => {
              try {
                let x = onRejected(this.reason);
                resolvePromise(promise2, x, resolve, reject);
              } catch (e) {
                reject(e);
              }
            }, 0);
          }
        });
        return promise2;
      };

      //catch
      Promise.prototype.catch = function (onRejected) {
        return this.then(null, onRejected);
      };

      /**
       * 解析then返回值与新Promise对象
       * @param {Object} 新的Promise对象，就是我们创建的promise2实例
       * @param {*} x 上一个then的返回值(已确定)
       * @param {Function} resolve promise2处理器函数的resolve
       * @param {Function} reject promise2处理器函数的reject
       */

      function resolvePromise(promise2, x, resolve, reject) {
        if (promise2 === x) {
          reject(new TypeError("请避免Promise循环引用"));
        }
      }

      let called;
      if (x !== null && (typeof x === "object" || typeof x === "function")) {
        //可能是个对象或是函数
        try {
          //尝试取出then方法引用
          let then = x.then;
          if (typeof then === "function") {
            then.call(
              x,
              (y) => {
                if (called) return;
                called = true;
                resolvePromise(promise2, y, resolve, reject);
              },
              (r) => {
                if (called) return;
                called = true;
                reject(r);
              }
            );
          } else {
            //对象
            resolve(x);
          }
        } catch (e) {
          if (called) return;
          called = true;
          reject(e);
        }
      } else {
        //普通值
        resolve(x);
      }
    </script>
  </body>
</html>
